### ISSUE TITLE
Issues in Building the Dev Container

### ISSUE THREAD

**Issue by amirmolavi** [ericmjl/llamabot#118]
I am trying to build the dev container and I am following the instructions in [here](docs/developer/devcontainer.md).
I have several issues:

1) pixi lock file is out dated: Build is failing. updating the pixi.lock resolves this issue:
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/8e9bcfa6-0686-4bc4-9670-d745b90acec5">
2) in line 41, above image, it says the linux-aarch64 is not part of the package, I fixed it by adding this platform to supported platforms in pyproject.toml
3) With this all packages are being installed but when I get to the `postCreateCommand` it fails. looks like the conda environment is not properly set within the container (check the [screenshot](<img width="891" alt="image" src="https://github.com/user-attachments/assets/80c10829-da91-443b-b4db-22b33f84f2a5">))

I am not sure what I am missing here in step 3. 

I think step one and two needed to be updated in the project, If you agree i will open a PR.

**Comment by ericmjl** [comment]
@amirmolavi thanks for posting here! Yes, I'm in agreement, I would love to be able to review your PR please!

**Comment by ericmjl** [comment]
@amirmolavi thank you for your PR! I think with it being closed out, we can also close this issue, is that right?

**Comment by amirmolavi** [comment]
yes, we have planned it out. The merged PR does not fix this immediately, but we know what is the issue and solution. 
Thanks for letting me to work on this.

**Comment by amirmolavi** [comment]
I am closing this issue. This is done and merged. Thanks @ericmjl for the opportunity.

**Comment by ericmjl** [comment]
Thank you, @amirmolavi, for helping out!
