### ISSUE TITLE
cli demos in Readme

### ISSUE THREAD

**Issue by amirmolavi** [ericmjl/llamabot#133]
the links for cli demos in the readme are broken and return 404
<img width="282" alt="image" src="https://github.com/user-attachments/assets/378366be-82da-4d5f-8d01-15f4f8150037">

**Comment by ericmjl** [comment]
Ack! That is a great find. Thank you, @amirmolavi -- I haven't been able to keep that up. 

Do you know if there is a pre-commit hook that we can use to check documentation links? I think we may want to get started with automating those checks.

**Comment by amirmolavi** [comment]
I am on it :)

**Comment by ericmjl** [comment]
Looks like we're good here! If you feel good about it, @amirmolavi, please feel free to close the issue!
