### ISSUE TITLE
Ollama QueryBot

### ISSUE THREAD

**Issue by ciri** [ericmjl/llamabot#15]
Following the documentation, we can create a SimpleBot that interfaces with Ollama as follows:

```
from llamabot import SimpleBot  # you can also use QueryBot or ChatBot

bot = SimpleBot("You are a conversation expert", model_name="mistral")
bot("hello")
```
```
> Hello! How can I assist you today?
> AIMessage(content='Hello! How can I assist you today?')
```
Doing the same with a QueryBot, however, does not seem to be support contrary to what is mentioned.

```
bot = QueryBot(
     "You are a bot that reads a PDF book and responds to questions about that book.",
     doc_paths=[pdf_fname],
     model_name='mistral'
)
bot('hello')
```
```
******
Could not load OpenAIEmbedding. Using HuggingFaceBgeEmbeddings with model_name=BAAI/bge-small-en. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

******
File [...\site-packages\llamabot\bot\querybot.py:188](.../llamabot/bot/querybot.py:188), in QueryBot.__call__(self, query, similarity_top_k)
    183 # Step 3: Stuff in as many source nodes as are permitted by the response token
    184 faux_chat_history.append(
    185     SystemMessage(content="Here is the context you will be working with:")
    186 )
    187 token_budget = (
--> 188     model_chat_token_budgets[self.model_name]
    189     - self.response_tokens
    190     - self.history_tokens
    191 )
    192 actual_source_nodes = []  # the actual source nodes that were stuffed in
    193 for n in source_nodes:

KeyError: 'mistral'
```

Furthermore, both classes also have potentially inaccurate documentation w.r.t. the model_name parameter.

**Update**: this seems to be an issue with mistral, it works with llama2.

**Comment by bdkech** [comment]
What version of transformers are you using? If you do a `pip install --upgrade transformers`, do you still see the issue?  This seems to be a documented issue on HuggingFace:  https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1#troubleshooting .

**Comment by ericmjl** [comment]
Hello @ciri! Firstly, thank you for catching the potential documentation errors here. Getting the docs up-to-date is important for the project.

Looking at the issue you've posted, I know what the immediate issue is -- `mistral` is not in the `model_chat_token_budgets` keys.

I can think of two ways to solve this issue, one temporary and one a bit more long-term sustainable.

The temp fix is to add mistral into the `model_chat_token_budgets` dictionary, which keeps track of model context sizes. Updating it is a bit of a pain though.

A longer-term fix would be to set a default value for the context window, likely the smallest context size amongst the most common models, so we no longer get the KeyError, though that doesn't solve the ability to keep an accurate mapping.

The best fix would be to have something like the Autoupdate Ollama Models pre-commit hooks I have in the repo, though it'd need something more complex, I think.

Regardless, I'm going to do both the short-term and long(er)-term fix in a coming PR, which is relatively easy.

Meanwhile, @ciri, would you be kind enough to help me pinpoint where the documentation is a bit out-of-date? That will help me figure out how to update it.

**Comment by ericmjl** [comment]
@ciri just a heads-up - I read through the auto-generated release notes and found that version 0.0.85 already has the default token budget calculation in place, so if you upgrade to latest llamabot, you should be able to eliminate this issue! Please let me know if you still encounter errors here.

**Comment by ericmjl** [comment]
Closing this issue as it's been open for a while now! If there's anything new that arises on this front, please feel free to ping in and re-open the issue :smile:.
