### ISSUE TITLE
Querybot issue docpath

### ISSUE THREAD

**Issue by jdanion** [ericmjl/llamabot#29]
Hi,

First of all thanks for your great work !

I try to use with zotero and i get this error when using : llamabot zotero chat

> 

Here is the end og the log

│ │       fpath = PosixPath('/tmp/SJU2E2SH.pdf')                             │ │
│ │     library = ZoteroLibrary(                                             │ │
│ │               │   zot=<pyzotero.zotero.Zotero object at 0x127b28ac0>,    │ │
│ │               │   json_dir=None,                                         │ │
│ │               │   articles_only=False                                    │ │
│ │               )                                                          │ │
│ │  model_name = 'mistral/mistral-medium'                                   │ │
│ │   paper_key = 'ISTWB7A4'                                                 │ │
│ │       query = ''                                                         │ │
│ │        sync = True                                                       │ │
│ │        task = 1                                                          │ │
│ │ user_choice = 'Review of fluorescence guided surgery systems:            │ │
│ │               identification of key performance'+46                      │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: QueryBot.__init__() got an unexpected keyword argument 'doc_paths' `

The pdf is well downloaded and present in /tmp/path.

So the problem comes from this part of the code 

│    97 │                                                                      │
│    98 │   with progress:                                                     │
│    99 │   │   task = progress.add_task("Embedding paper and initializing bot │
│ ❱ 100 │   │   docbot = QueryBot(docbot_sysprompt(), doc_paths=[fpath], model │
│   101 │   │   progress.remove_task(task)                                     │
│   102 │                                                                      │
│   103 │   # From this point onwards, we need to record the chat.    

I use local mistral llm.

Thanks for your help

And again great project, i've got tons of ideas to use it !

**Comment by ericmjl** [comment]
Hi @jdanion, this looks like a bug in llamabot zotero chat. I have yet to update it. Thank you for the bug catch, I think I know what the fix is here.

Meanwhile, if you're in a rush, could you install an earlier version of `llamabot` for now? That might fix the issue. I would recommend `llamabot==0.0.89`, which is a tad old, but uses the older bot interface before I did the refactor to make further development on `llamabot` easier.

**Comment by ericmjl** [comment]
@jdanion I updated llamabot to version 0.2.3. I think this may fix the issue. Please let me know if you still see the error!

**Comment by ericmjl** [comment]
(Also, I'm envous that you get to use local mistral -- what are the specs on your machine? Believe it or not, I'm doing all of my work with a puny 16GB M1 Mac :smile:, and I'm on the brink of not having enough RAM for mistral-7b.)
