### ISSUE TITLE
Remove space at the beginning of generated response content

### ISSUE THREAD

**Issue by aidanbrewis** [ericmjl/llamabot#30]
I love this project, I noticed while using a ChatBot with stream=False that the content on the response always has a space at the start of it, this could be easily solved by adding .strip() when setting the content in generate_response in simplebot.py

This issue comes from ollama's content always having a space at the start.

could I please have permission to create a branch and open a small PR to add this ?

**Comment by ericmjl** [comment]
@aidanbrewis thank you for chiming in!

Yes, I would love to review a PR from you. Would you be kind enough to make one?

I am assuming you know how most PRs happen, but in case we need a refresher, the way to go about this would be to:

1. Fork the repo to your account, 
2. Create a new branch on the forked repo,
3. Make edits in that new branch,
4. Create PR with the base branch being aidenbrewis/llamabot/your-branch and the target branch being ericmjl/llamabot/main.

Please let me know if you need more help!

**Comment by aidanbrewis** [comment]
Thanks for the guidance @ericmjl this is my first contribution to an open source project, I didn't realise I had to fork the repo, I've opened [a PR for this issue](https://github.com/ericmjl/llamabot/pull/33)

**Comment by ericmjl** [comment]
Thanks a ton for your PR, @aidanbrewis! I have just cut a new release, version 0.2.1, which incorporates your changes.

I hope you enjoyed your first OSS contribution experience! As someone whose career was helped immensely by my OSS contributions, I hope this is your first step to doing cool stuff in the future!

**Comment by aidanbrewis** [comment]
Thanks for the opportunity and support @ericmjl I'm looking forward to contribute more, I'm very excited about the possibilities of local LLMs and doing lot's of experimenting. I believe this project is the state of the art for programmatic interfaces to local LLMs.
