### ISSUE TITLE
llamabot page is 404

### ISSUE THREAD

**Issue by jwuphysics** [ericmjl/llamabot#44]
The page https://ericmjl.github.io/llamabot/ results in a 404 error.

![image](https://github.com/ericmjl/llamabot/assets/3582121/c3a2486a-1562-4ea9-970b-4924745c24ff)

**Comment by ericmjl** [comment]
@jwuphysics thank you for reporting! I have put in a fix for the matter, should be live soon.

**Comment by ericmjl** [comment]
Confirming that the page is now up. Closing this issue!
