### ISSUE TITLE
docs: add some usage tips for `SimpleBot`, `ChatBot`, and `QueryBot`

### ISSUE THREAD

**Issue by reka** [ericmjl/llamabot#62]
* mention the `model_name` parameter explicitly in the docs for `SimpleBot`, `ChatBot`, and `QueryBot`

`QueryBot`

* Update param names `system_prompt` and `collection_name`
* Don't start with a huge dir.

**Comment by ericmjl** [comment]
This issue can be closed! Thank you, @reka :smile:
