### ISSUE TITLE
Support for Azure OpenAI API

### ISSUE THREAD

**Issue by sivagowrisankar** [ericmjl/llamabot#99]
This is not a bug or an issue per se, but more of a guidance question. 
We are trying to use LlamaBot with Azure OpenAI API and was wondering if there is a easy config change that I can make (i.e., setting up env variables or passing arguments) that makes this possible. I have tried setting env variables, but the CLIs for, for e.g., docs write or for that matter SimpleBot and ChatBot seems to assume OpenAI API or Ollama. 

Great work by the way.
Siva

**Comment by ericmjl** [comment]
Hi @sivagowrisankar! Thanks for chiming in!

Underneath the hood, LlamaBot uses LiteLLM to route to different API providers. I went digging into the docs. It looks like to connect with Azure, you'll need to set three environment variables:

```python
os.environ["AZURE_API_KEY"] = ""
os.environ["AZURE_API_BASE"] = ""
os.environ["AZURE_API_VERSION"] = ""
```

and prefix all model names with `azure`, as follows:

```python
    ...,
    model_name = "azure/<your_deployment_name>",
    ...,
```

Hope this helps!

Please let me know if you'd like to chat further. Happy to schedule a call via [Calendly](https://calendly.com/ericmjl/llm-chat-1).

**Comment by ericmjl** [comment]
@sivagowrisankar I'm going to close the issue for now, but please feel free to reopen if you've got follow-up questions!
